# -*- coding: utf-8 -*-
"""Pandas Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3molTUQT2siUH4JY47Hici_61A2zzPF
"""

import pandas as pd
# when data contains scaler value
Data=[1,2,3,4,'Mahaveer']
s=pd.Series(Data)
s

# when data contains dictionary
data={'A':2,'B':4,'C':6,'D':8}
data

sd=pd.Series(data)
sd

#when data contains Ndarray
DATA=[[1,2,3,],[4,5,6]]
snd= pd.Series(DATA)
snd
